@startuml
skinparam classAttributeIconSize 0

Class "WarehouseUI"{
}

Class "WarehouseController"{
+buildWarehouse(fileName)

+repositories()
+warehouses()
+saveWarehouse()
}




Class "Warehouse"{
     -Name name;
     -Vat vat;
     -Date dateOfBirth;
     -PhoneNumber phoneNumber;
     -Address address;
}







class WarehouseBuilder {
+readFromJson((fileName)
}

class PersistenceContext {
-Logger LOGGER
-RepositoryFactory theFactory
+repositories()
}

class RepositoryFactory{
+warehouses()
}

class WarehouseRepository{
+findById(Long number)
}


WarehouseUI ..> WarehouseController
WarehouseController..> WarehouseBuilder
WarehouseBuilder "1" --> "*" Warehouse : builds

Aisle "0..*" <-u- "1" Warehouse : contains
Row "0..*" <-r- "1" Aisle : contains
Shelf "0..*" <-u- "1" Row : contains
Bin "0..*" <-l- "1" Shelf : contains


"WarehouseController" "1" --> "1" "PersistenceContext" :creates


"PersistenceContext" "1" --> "1" "RepositoryFactory" :creates


"RepositoryFactory" "1" --> "1" "WarehouseRepository"  :creates

"WarehouseController" "1" --> "1..*" "Warehouse" :saves

"Warehouse" "1" --> "1" "WarehouseRepository" :in

@enduml