@startuml
hide methods
hide fields


package "Product Category" <<Rectangle>>{

    class "Product Category" << (E,#FFFFFF) >> <<Root>>

}

package Customer <<rectangle>>{

class "Customer" << (E,#FFFFFF) >> <<Root>>

class "Shopping Cart" << (E,#FFFFFF) >> 

Customer "1" --> "1" "Shopping Cart"

}

package Product <<rectangle>>{

    class Product << (E,#FFFFFF) >> <<Root>>

    class Description<< (V,#AAAAAA) >>
    class Brand << (V,#AAAAAA) >>
    class Photo << (V,#AAAAAA) >>
    class Reference << (V,#AAAAAA) >>
    class Barcode << (V,#AAAAAA) >>
    class "Production Code" << (V,#AAAAAA) >>
    class Price << (V,#AAAAAA) >>

    Product --> Description
    Product --> Brand 
    Product --> Photo 
    Product --> Reference
    Product --> Barcode 
    Product --> "Production Code"
    Product --> Price 

}



   class Catalog << (E,#FFFFFF) >>

 


"Product Category" "1" --> "0..*" Product
Catalog  "1" -r-> "0..*" Product

"Shopping Cart" "*" --> "1" Catalog

@enduml