@startuml
hide methods


class User << (E,#FFFFFF) >> << Root >>

package WarehouseEmployee <<rectangle>>{

class WarehouseEmployee << (E,#FFFFFF) >> <<Root>>

}

package SalesClerk <<rectangle>>{

class SalesClerk << (E,#FFFFFF) >> <<Root>>

}

package SalesManager <<rectangle>>{

class SalesManager << (E,#FFFFFF) >> <<Root>>

}

package Administrator <<rectangle>>{

class Administrator << (E,#FFFFFF) >> <<Root>>{
}

}

package "Shopping Cart" <<rectangle>>{     

class "Shopping Cart" << (E,#FFFFFF) >> << Root >> 

}

package Customer <<rectangle>>{     

class Customer << (E,#FFFFFF) >> <<Root>>



class "Purchase History" << (E,#FFFFFF) >> 

    Customer "1" --> "1" "Purchase History"
}

package Warehouse <<rectangle>>{

class Warehouse << (V,#FFFFFF) >> <<Root>>

class Aisle << (E,#FFFFFF) >> 

class Rows << (E,#FFFFFF) >> 

class Shelf << (E,#FFFFFF) >> 

class Bin << (E,#FFFFFF) >> 

Warehouse "1" --> "1..*" Aisle 
Aisle "1" --> "1..*" Rows 
Rows "1" --> "1..*" Shelf 
Shelf "1" --> "1..*" Bin 

}

package AVG <<rectangle>>{

class AVG << (E,#FFFFFF) >> <<Root>>

class AVGState << (V,#FFFFFF) >> 

AVG "1" --> "1" AVGState 

}

package Survey <<rectangle>>{

class Survey << (E,#FFFFFF) >> <<Root>> {
-description
}


class "Alphanumeric code" << (V,#FFFFFF) >>

class "Period of days" << (V,#FFFFFF) >>

class "Rules" << (V,#FFFFFF) >>

    Survey "1" --> "1" "Alphanumeric code"
    Survey "1" --> "1" "Period of days"
    Survey "1" --> "1..*" "Rules"
}

package "Question Type" <<rectangle>> {
class "Question Type" << (E,#FFFFFF) >> <<Root>>
}

package Section <<rectangle>> {
class Section << (E,#FFFFFF) >> << root >>  {
-description
}
class "Section Id" << (V,#FFFFFF) >> 

class Repeatability << (V,#FFFFFF) >> 

class "Section Title"  << (V,#FFFFFF) >> 

Section "1" --> "1" "Section Id"

Section "1" --> "1" "Section Title"

Section "1" --> "1" Repeatability


}

package Question <<rectangle>>{
class Question << (E,#FFFFFF) >> << root >>{
-question
-instruction
-additionalInfo
}

Question "1" --> "1..*" "Question Id"
}




package Questionnaire <<rectangle>> {

class Questionnaire << (E,#FFFFFF) >> <<Root>> {
-welcomeMessage
-finalMessage
}

class "Questionnaire Id" << (V,#FFFFFF) >> 

class "Questionnaire Title"  << (V,#FFFFFF) >> 



class "Question Id" << (V,#FFFFFF) >> 

Questionnaire "1" --> "1..*" Section

Questionnaire "1" --> "1" "Questionnaire Id"

Questionnaire "1" --> "1" "Questionnaire Title" 

}




package Order <<rectangle>>{

    class Order << (E,#FFFFFF) >> <<Root>>

    class Payment << (V,#AAAAAA) >>

    class Shipment << (V,#AAAAAA) >>

    class "Order State" << (V,#AAAAAA) >>


    Order --> Payment 
    Order --> Shipment 
    Order --> "Order State"
}

package Product <<rectangle>>{

    class Product << (E,#FFFFFF) >> <<Root>>

    class Description<< (V,#AAAAAA) >>
    class Brand << (V,#AAAAAA) >>
    class Photo << (V,#AAAAAA) >>
    class Reference << (V,#AAAAAA) >>
    class Barcode << (V,#AAAAAA) >>
    class "Production Code" << (V,#AAAAAA) >>
    class Price << (V,#AAAAAA) >>

    Product --> Description
    Product --> Brand 
    Product --> Photo 
    Product --> Reference
    Product --> Barcode 
    Product --> "Production Code"
    Product --> Price 

}

package "Product Category" <<Rectangle>>{

    class "Product Category" << (E,#FFFFFF) >> <<Root>>

}




 class Catalog << (E,#FFFFFF) >>

 class "Obligatoriness" << (V,#FFFFFF) >> 


"Product Category" "1" --> "0..*" Product
Catalog  "1" -r-> "0..*" Product
Customer "1" --> "0..*" Order
Survey "1" --> "0..*" Questionnaire
Customer "1" --> "0..*" Questionnaire
Warehouse"1" --> "0..*" AVG
Section "1" --> "1..*" Question
Section "1" --> "1" "Obligatoriness"
Question "1" --> "1" "Obligatoriness"
Customer "1" --> "1" "Shopping Cart"
"Shopping Cart" "1" --> "1" Catalog
User "1" --|> "0..*" Customer
User "1" --|> "0..*" WarehouseEmployee
User "1" --|> "0..*" SalesClerk
User "1" --|> "0..*" Administrator
User "1" --|> "0..*" SalesManager
@enduml