@startuml
hide methods



package User <<rectangle>>{

class User << (E,#FFFFFF) >> << Root >>
     
}

package Customer <<rectangle>>{

class Customer << (E,#FFFFFF) >> <<Root>>

class "Shopping Cart" << (E,#FFFFFF) >> 

class "Purchase History" << (E,#FFFFFF) >> 

    Customer "1" --> "1" "Shopping Cart"
    Customer "1" --> "1" "Purchase History"
}

package Warehouse <<rectangle>>{

class Warehouse << (V,#FFFFFF) >> <<Root>>

class Aisle << (E,#FFFFFF) >> 

class Rows << (E,#FFFFFF) >> 

class Shelf << (E,#FFFFFF) >> 

class Bin << (E,#FFFFFF) >> 

Warehouse "1" --> "1..*" Aisle 
Aisle "1" --> "1..*" Rows 
Rows "1" --> "1..*" Shelf 
Shelf "1" --> "1..*" Bin 

}

package AVG <<rectangle>>{

class AVG << (E,#FFFFFF) >> <<Root>>

class AVGState << (V,#FFFFFF) >> 

AVG "1" --> "1" AVGState 

}

package Survey <<rectangle>>{

class Survey << (E,#FFFFFF) >> <<Root>> {
-description
}

class "Alphanumeric code" << (V,#FFFFFF) >>

class "Period of days" << (V,#FFFFFF) >>

class "Rules" << (V,#FFFFFF) >>

    Survey "1" --> "1" "Alphanumeric code"
    Survey "1" --> "1" "Period of days"
    Survey "1" --> "1..*" "Rules"
}

package "Question Type" <<rectangle>> {
class "Question Type" << (E,#FFFFFF) >> <<Root>>
}

package Questionnaire <<rectangle>> {

class Questionnaire << (E,#FFFFFF) >> <<Root>> {
-welcomeMessage
-finalMessage
}

class Section << (E,#FFFFFF) >>  {
-description
}

class Question << (E,#FFFFFF) >> {
-question
-instruction
-additionalInfo
}

class "Questionnaire Id" << (V,#FFFFFF) >> 

class Title << (V,#FFFFFF) >> 

class "Obligatoriness" << (V,#FFFFFF) >> 

class "Section Id" << (V,#FFFFFF) >> 

class "Question Id" << (V,#FFFFFF) >> 

class Repeatability << (V,#FFFFFF) >> 

class Content << (V,#FFFFFF) >> 


Questionnaire "1" --> "1..*" Section

Questionnaire "1" --> "1" "Questionnaire Id"

Questionnaire "1" --> "1" Title 

Section "1" --> "1" "Obligatoriness"

Section "1" --> "1" "Section Id"

Section "1" --> "1" Title 

Section "1" --> "1" Content 

Section "1" --> "1" Repeatability

Content "1" --> "1..*" Question

Question "1" --> "1..*" "Question Id"

Question "1" --> "1" Obligatoriness 
}




package Order <<rectangle>>{

    class Order << (E,#FFFFFF) >> <<Root>>

    class Payment << (V,#AAAAAA) >>

    class Shipment << (V,#AAAAAA) >>

    class "Order State" << (V,#AAAAAA) >>


    Order --> Payment 
    Order --> Shipment 
    Order --> "Order State"
}

package Product <<rectangle>>{

    class Product << (E,#FFFFFF) >> <<Root>>

    class Description<< (V,#AAAAAA) >>
    class Brand << (V,#AAAAAA) >>
    class Photo << (V,#AAAAAA) >>
    class Reference << (V,#AAAAAA) >>
    class Barcode << (V,#AAAAAA) >>
    class "Production Code" << (V,#AAAAAA) >>
    class Price << (V,#AAAAAA) >>

    Product --> Description
    Product --> Brand 
    Product --> Photo 
    Product --> Reference
    Product --> Barcode 
    Product --> "Production Code"
    Product --> Price 

}

package "Product Category" <<Rectangle>>{

    class "Product Category" << (E,#FFFFFF) >> <<Root>>

}




   class Catalog << (E,#FFFFFF) >>

 


"Product Category" "1" --> "0..*" Product
Catalog  "1" -r-> "0..*" Product
Customer "1" --> "0..*" Order
Survey "1" --> "0..*" Questionnaire
Customer "1" --> "0..*" Questionnaire
Warehouse"1" --> "0..*" AVG
@enduml